### HOMEWORK

In [3]:
import numpy as np

## 10

In [2]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [24]:
n1=np.array([1,2,3,4])
n2=np.array([1,6,0,4])
np.greater(n2,n1)


array([False,  True, False, False])

In [20]:
np.greater_equal(n1,n2)

array([ True, False,  True,  True])

In [22]:
np.less_equal(n2,n1)

array([ True, False,  True,  True])

In [21]:
np.less(n2,n1)

array([False, False, False, False])

### 12

In [27]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [118]:
n=np.array([2,4,5,6,7])
print(f"there is {n.size} elements")
print(f"each one occupies {n.itemsize} bites")
print(f"together {n.size * n.itemsize} bites")

there is 5 elements
each one occupies 8 bites
together 40 bites


## 18

In [33]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.



In [40]:
n=np.random.normal(0,1,15)
n

array([ 1.66781223,  0.82559064, -0.01886982,  0.8132544 ,  0.11824112,
       -0.99803766,  0.32480933,  1.87238717, -0.1419588 ,  0.44657182,
        1.37680192, -0.49790774, -1.55168619,  0.19359077, -0.11827438])

## 19

In [ ]:
#Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [42]:
n=np.arange(15,55)
n[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

## 21

In [43]:
#Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.


In [52]:
n=np.linspace(5,50,10,endpoint=True)

In [53]:
n

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

## 22

In [54]:
#Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [72]:
n=np.arange(0,20)
n= np.concatenate([n[:9], -n[9:15]])
n


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14])

## 23

In [73]:
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.



In [76]:
n=np.random.randint(0,10,5)
n

array([1, 4, 2, 6, 3])

## 24

In [77]:
#Write a NumPy program to multiply the values of two given vectors.



In [78]:
a=np.array([1,2,3,4])
b=np.array([2,1,2,2])
a*b

array([2, 2, 6, 8])

## 25

In [79]:
#Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.



In [85]:
a=np.arange(10,22).reshape(3,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## 26

In [86]:
#Write a NumPy program to find the number of rows and columns in a given matrix.




In [87]:
a=np.array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])
a.shape

(3, 4)

## 27

In [88]:
#Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.



In [89]:
n=np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 28

In [101]:
#Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [102]:
a=np.ones([10,10])
a
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 29

In [103]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.



In [107]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

## 31

In [109]:
#Write a NumPy program to create a 3x3x3 array filled with arbitrary values.



In [117]:
n=np.random.random((3,3,3))
n

array([[[0.50668492, 0.26476256, 0.38044232],
        [0.48999451, 0.55550159, 0.16860337],
        [0.82402485, 0.35037564, 0.90789709]],

       [[0.45355633, 0.13606908, 0.60840186],
        [0.33015462, 0.10856489, 0.32653509],
        [0.88473467, 0.818544  , 0.33791621]],

       [[0.66112668, 0.47521385, 0.57455704],
        [0.81160406, 0.25647668, 0.02830597],
        [0.91274565, 0.52063835, 0.61047057]]])