In [155]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor

In [156]:
data=pd.read_csv("Student_Performance.csv")
data

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [157]:
data.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 893.6 KB


In [158]:
y=data["Performance Index"]
x=data.drop("Performance Index",axis=1)

In [159]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.25, random_state=0)


In [160]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((7500, 5), (2500, 5), (7500,), (2500,))

In [161]:
data["Hours Studied"]=data["Hours Studied"].astype("int8")

In [162]:
data.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int8   
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(3), int8(1), object(1)
memory usage: 825.3 KB


In [163]:
scaler=MinMaxScaler()
x_hs_train_sc=pd.DataFrame(scaler.fit_transform(x_train[["Hours Studied"]]),columns=["Hours Studied"],
    index=x_train.index)
x_hs_test_sc=pd.DataFrame(scaler.transform(x_test[["Hours Studied"]]),columns=["Hours Studied"],
    index=x_test.index)


x_train["Hours Studied"]=x_hs_train_sc
x_test["Hours Studied"]=x_hs_test_sc


In [164]:
scaler=MinMaxScaler()
x_ps_train_sc=pd.DataFrame(scaler.fit_transform(x_train[["Previous Scores"]]),columns=["Previous Scores"],
    index=x_train.index)
x_ps_test_sc=pd.DataFrame(scaler.transform(x_test[["Previous Scores"]]),columns=["Previous Scores"],
    index=x_test.index)


x_train["Previous Scores"]=x_ps_train_sc
x_test["Previous Scores"]=x_ps_test_sc
x_train

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
2967          0.750         0.237288                         No            8   
700           0.250         0.440678                         No            4   
3481          0.125         0.949153                        Yes            9   
1621          0.375         0.000000                        Yes            4   
800           0.625         0.135593                        Yes            4   
...             ...              ...                        ...          ...   
9225          0.500         0.406780                        Yes            4   
4859          0.625         0.644068                         No            9   
3264          0.000         0.610169                        Yes            6   
9845          0.375         0.067797                         No            4   
2732          0.875         0.728814                        Yes            8   

      Sample Question Papers Practiced  
2967                                 3  
700                                  6  
3481                                 8  
1621                                 0  
800                                  1  
...                                ...  
9225                                 3  
4859                                 6  
3264                                 5  
9845                                 8  
2732                                 1  

[7500 rows x 5 columns]

In [165]:
data.drop("Extracurricular Activities",axis=1,inplace=True)

In [166]:
scaler=MinMaxScaler()
x_sleep_train_sc=pd.DataFrame(scaler.fit_transform(x_train[["Sleep Hours"]]),columns=["Sleep Hours"],index=x_train.index)
x_sleep_test_sc=pd.DataFrame(scaler.transform(x_test[["Sleep Hours"]]),columns=["Sleep Hours"],index=x_test.index)

x_train["Sleep Hours"]=x_sleep_train_sc
x_test["Sleep Hours"]=x_sleep_test_sc

In [167]:
x_train

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
2967          0.750         0.237288                         No          0.8   
700           0.250         0.440678                         No          0.0   
3481          0.125         0.949153                        Yes          1.0   
1621          0.375         0.000000                        Yes          0.0   
800           0.625         0.135593                        Yes          0.0   
...             ...              ...                        ...          ...   
9225          0.500         0.406780                        Yes          0.0   
4859          0.625         0.644068                         No          1.0   
3264          0.000         0.610169                        Yes          0.4   
9845          0.375         0.067797                         No          0.0   
2732          0.875         0.728814                        Yes          0.8   

      Sample Question Papers Practiced  
2967                                 3  
700                                  6  
3481                                 8  
1621                                 0  
800                                  1  
...                                ...  
9225                                 3  
4859                                 6  
3264                                 5  
9845                                 8  
2732                                 1  

[7500 rows x 5 columns]

In [168]:
d=x_train["Extracurricular Activities"].value_counts()
d

Extracurricular Activities
No     3757
Yes    3743
Name: count, dtype: int64

In [169]:
x_train["Extracurricular Activities"] = (x_train["Extracurricular Activities"] == "Yes").astype("int8")
x_test["Extracurricular Activities"] = (x_test["Extracurricular Activities"] == "Yes").astype("int8")


In [170]:
x_test

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
9394          0.375         0.457627                           0          1.0   
898           0.875         0.338983                           0          0.0   
2398          0.625         0.847458                           0          0.2   
5906          0.000         0.186441                           1          0.4   
2343          0.125         0.847458                           0          0.2   
...             ...              ...                         ...          ...   
8764          0.750         0.000000                           0          0.8   
4359          0.375         0.033898                           1          0.2   
2041          0.875         0.169492                           0          0.8   
1108          0.750         0.559322                           1          1.0   
3332          0.625         0.898305                           1          1.0   

      Sample Question Papers Practiced  
9394                                 3  
898                                  7  
2398                                 6  
5906                                 6  
2343                                 9  
...                                ...  
8764                                 8  
4359                                 7  
2041                                 7  
1108                                 5  
3332                                 5  

[2500 rows x 5 columns]

In [171]:
scaler=MinMaxScaler()
x_pp_train_sc=pd.DataFrame(scaler.fit_transform(x_train[["Sample Question Papers Practiced"]]),columns=["Sample Question Papers Practiced"],index=x_train.index)
x_pp_test_sc=pd.DataFrame(scaler.transform(x_test[["Sample Question Papers Practiced"]]),columns=["Sample Question Papers Practiced"],index=x_test.index)

x_train["Sample Question Papers Practiced"]=x_pp_train_sc
x_test["Sample Question Papers Practiced"]=x_pp_test_sc

In [172]:
x_train

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
2967          0.750         0.237288                           0          0.8   
700           0.250         0.440678                           0          0.0   
3481          0.125         0.949153                           1          1.0   
1621          0.375         0.000000                           1          0.0   
800           0.625         0.135593                           1          0.0   
...             ...              ...                         ...          ...   
9225          0.500         0.406780                           1          0.0   
4859          0.625         0.644068                           0          1.0   
3264          0.000         0.610169                           1          0.4   
9845          0.375         0.067797                           0          0.0   
2732          0.875         0.728814                           1          0.8   

      Sample Question Papers Practiced  
2967                          0.333333  
700                           0.666667  
3481                          0.888889  
1621                          0.000000  
800                           0.111111  
...                                ...  
9225                          0.333333  
4859                          0.666667  
3264                          0.555556  
9845                          0.888889  
2732                          0.111111  

[7500 rows x 5 columns]

In [173]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [174]:
y_pred_test=model.predict(x_test)
y_pred_test

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:293: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:293: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:293: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_


array([50.45690146, 53.09930205, 78.25332644, ..., 44.82033293,
       66.16369669, 83.69119201], shape=(2500,))

In [175]:
y_test.values

array([53., 50., 80., ..., 46., 66., 84.], shape=(2500,))

In [176]:
mae=mean_absolute_error(y_test,y_pred_test)
mae

1.6101268935152795

In [181]:
model=KNeighborsRegressor(n_neighbors=3)
model.fit(x_train,y_train)
y_pred_test2=model.predict(x_test)
y_pred_test2[]

array([48.33333333, 56.        , 76.33333333, ..., 46.33333333,
       68.        , 86.        ], shape=(2500,))

In [178]:
y_test.values

array([53., 50., 80., ..., 46., 66., 84.], shape=(2500,))

In [179]:
mae=mean_absolute_error(y_test,y_pred_test)
mae

1.6101268935152795